export const palette = {
  transparent: 'transparent',
  white: '#ffffff',
  mariner: '#2574db',
  palesky: '#6b7786',
  loblolly: '#bfc6ce',
  mineshaft: '#333333',
  jordyblue: '#9AB3F5',
  maize: '#F6D6AD',
  gullgray: '#9FA9B7',
  razzmatazz: '#E60C51',
  limeade: '#599900',
  tangerine: '#e39b00',
  regentgray: '#838fa0',
  hawkesblue: '#f0f6fe',
  blackhaze: '#F1F3F3',
  black: '#000000',
};

export const colors = {
  'transparent': palette.transparent,
  'black': palette.black,
  'white': palette.white,
  'primary': palette.mariner,
  'primaryLight': palette.hawkesblue,
  'secondary': palette.palesky,
  'secondaryLight': palette.blackhaze,
  'quaternary': palette.loblolly,
  'disabled': palette.gullgray,
  'success': palette.limeade,
  'warning': palette.tangerine,
  'error': palette.razzmatazz,
  'info': palette.jordyblue,
  'text': palette.mineshaft,
  'border': palette.regentgray,
};
